<%@ Page Title="" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="ListarRemolque.aspx.cs" Inherits="SiCoVe.ListarRemolque" %>
<asp:Content ID="Content1" ContentPlaceHolderID="IncludeCssSection" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="PaginaCentral_ContentPlaceHolder" runat="server">
            <div id="page-wrapper">
        <div class="panel panel-default">
            <div class="panel-heading">
               Remolques
            </div>
            <div class="panel-body">
                <div class="row">
          
                    <div class="form-group">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:Label ID="LblLegajo" runat="server" Text="Label">Legajo</asp:Label>
                        :
                        <asp:DropDownList ID="DdlLegajo" runat="server"></asp:DropDownList>
                        &nbsp;
                        <asp:Label ID="LblApellido" runat="server" Text="Label">Apellido</asp:Label>
                        :&nbsp;&nbsp;
                        <asp:TextBox ID="TxtApellido" runat="server"></asp:TextBox>
                        &nbsp;
                        <asp:Label ID="LblNombre" runat="server" Text="Label">Nombre</asp:Label>
                        :&nbsp;
                        <asp:TextBox ID="TxtNombre" runat="server"></asp:TextBox>

                        &nbsp;

                        <asp:Button ID="BtnBuscar" runat="server" Text="Buscar" />
                        <br />
                    </div>
                    <div class="form-group">
                          &nbsp;<asp:GridView ID="GvRemolque" runat="server" AutoGenerateColumns="False" BorderColor="#DEDFDE" BorderWidth="1px" AllowCustomPaging="True" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" CellPadding="4" ForeColor="Black" GridLines="Vertical" style="margin-left: 93px" Width="399px" PageSize="20">
                              <AlternatingRowStyle BackColor="White" Wrap="True" />
                            <Columns>
                                <asp:BoundField HeaderText="DNI"/>
                                <asp:BoundField HeaderText="Apellido" />
                                <asp:BoundField HeaderText="Nombres" />
                                <asp:BoundField HeaderText="Sexo" />
                                <asp:BoundField HeaderText="Fecha de nacimiento" />
                                <asp:BoundField HeaderText="Lugar de nacimiento" />
                                <asp:BoundField HeaderText="Domicilio" />
                                <asp:BoundField HeaderText="Piso" />
                                <asp:BoundField HeaderText="Departamento" />
                                <asp:BoundField HeaderText="Localidad" />
                                <asp:BoundField HeaderText="Legajo" />
                                
                            </Columns>
                              <EditRowStyle BorderWidth="100px" />
                              <FooterStyle BackColor="#CCCC99" />
                              <HeaderStyle BackColor="#6B696B" Font-Bold="True" Font-Names="Cambria" Font-Size="Small" ForeColor="White" />
                              <PagerStyle BackColor="#F7F7DE" BorderColor="Black" ForeColor="Black" HorizontalAlign="Right" />
                              <RowStyle BackColor="#F7F7DE" />
                              <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                              <SortedAscendingCellStyle BackColor="#FBFBF2" />
                              <SortedAscendingHeaderStyle BackColor="#848384" />
                              <SortedDescendingCellStyle BackColor="#EAEAD3" />
                              <SortedDescendingHeaderStyle BackColor="#575357" />
                        </asp:GridView>
                        </div>
                 </div>
            </div>  
        </div>         
    </div>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="includeJsSection" runat="server">
</asp:Content>
