//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseSiCoVe
{
    using System;
    using System.Collections.Generic;
    
    public partial class cedula
    {
        public int id { get; set; }
        public string nro_cedula { get; set; }
        public int persona_id { get; set; }
        public int uso_id { get; set; }
        public int estado_id { get; set; }
        public int vehiculo_id { get; set; }
        public System.DateTime vencimiento { get; set; }
        public bool flag_autorizado { get; set; }
    
        public virtual estado_cedula estado_cedula { get; set; }
        public virtual persona persona { get; set; }
        public virtual uso_cedula uso_cedula { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
