//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseSiCoVe
{
    using System;
    using System.Collections.Generic;
    
    public partial class cedula
    {
        public int id { get; set; }
        public string nro_cedula { get; set; }
        public int persona_id { get; set; }
        public int uso_id { get; set; }
        public int estado_id { get; set; }
        public int vehiculo_id { get; set; }
        public System.DateTime vencimiento { get; set; }
        public bool flag_autorizado { get; set; }
    
        public virtual estado_cedula estado_cedula { get; set; }
        public virtual persona persona { get; set; }
        public virtual uso_cedula uso_cedula { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
