//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseSiCoVe
{
    using System;
    using System.Collections.Generic;
    
    public partial class denuncia
    {
        public int id { get; set; }
        public int usuario_id { get; set; }
        public int estado_id { get; set; }
        public Nullable<int> infraccion_id { get; set; }
        public string dominio { get; set; }
        public string ubicacion { get; set; }
        public byte[] adjunto { get; set; }
        public string ruta_adjunto { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string observaciones { get; set; }
        public int localidad_id { get; set; }
    
        public virtual estado_denuncia estado_denuncia { get; set; }
        public virtual localidad localidad { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual infraccion infraccion { get; set; }
    }
}
