//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseSiCoVe
{
    using System;
    using System.Collections.Generic;
    
    public partial class infraccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public infraccion()
        {
            this.denuncias = new HashSet<denuncia>();
        }
    
        public int id { get; set; }
        public int agente_transito_id { get; set; }
        public int vehiculo_id { get; set; }
        public int licencia_id { get; set; }
        public int codigo_infraccion_id { get; set; }
        public int provincia_id { get; set; }
        public int localidad_id { get; set; }
        public Nullable<int> control_id { get; set; }
        public Nullable<long> nro_acta { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string locacion { get; set; }
        public string observaciones { get; set; }
        public string documentacion_retenida { get; set; }
        public string lugar_retencion { get; set; }
        public Nullable<int> persona_id { get; set; }
        public Nullable<int> vehiculo_tipo_id { get; set; }
        public Nullable<int> vehiculo_marca_id { get; set; }
        public string vehiculo_modelo { get; set; }
        public string vehiculo_dominio { get; set; }
        public string imputado_apellido { get; set; }
        public string imputado_nombre { get; set; }
        public Nullable<long> imputado_dni { get; set; }
        public Nullable<int> imputado_provincia_id { get; set; }
        public Nullable<int> imputado_localidad_id { get; set; }
        public string imputado_domicilio { get; set; }
        public string imputado_nropuerta { get; set; }
        public Nullable<short> imputado_piso { get; set; }
        public string imputado_departamento { get; set; }
        public string imputado_licencia_nro { get; set; }
        public Nullable<int> imputado_licencia_municipio_id { get; set; }
        public Nullable<int> imputado_licencia_categoria_id { get; set; }
    
        public virtual categoria_licencia categoria_licencia { get; set; }
        public virtual codigo_infraccion codigo_infraccion { get; set; }
        public virtual localidad localidad { get; set; }
        public virtual licencia licencia { get; set; }
        public virtual localidad localidad1 { get; set; }
        public virtual marca_vehiculo marca_vehiculo { get; set; }
        public virtual municipio municipio { get; set; }
        public virtual persona persona { get; set; }
        public virtual provincia provincia { get; set; }
        public virtual tipo_vehiculo tipo_vehiculo { get; set; }
        public virtual vehiculo vehiculo { get; set; }
        public virtual control control { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<denuncia> denuncias { get; set; }
    }
}
