//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseSiCoVe
{
    using System;
    using System.Collections.Generic;
    
    public partial class infraccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public infraccion()
        {
            this.denuncias = new HashSet<denuncia>();
        }
    
        public int id { get; set; }
        public int agente_transito_id { get; set; }
        public int vehiculo_id { get; set; }
        public int licencia_id { get; set; }
        public int codigo_infraccion_id { get; set; }
        public int provincia_id { get; set; }
        public int localidad_id { get; set; }
        public int control_id { get; set; }
        public Nullable<long> nro_acta { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string locacion { get; set; }
        public string observaciones { get; set; }
        public string documentacion_retenida { get; set; }
        public string lugar_retencion { get; set; }
        public string dominio { get; set; }
    
        public virtual codigo_infraccion codigo_infraccion { get; set; }
        public virtual control control { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<denuncia> denuncias { get; set; }
        public virtual licencia licencia { get; set; }
        public virtual localidad localidad { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
