//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseSiCoVe
{
    using System;
    using System.Collections.Generic;
    
    public partial class licencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public licencia()
        {
            this.infraccions = new HashSet<infraccion>();
        }
    
        public int id { get; set; }
        public string nro_licencia { get; set; }
        public int categoria_id { get; set; }
        public int persona_id { get; set; }
        public int municipio_id { get; set; }
        public string clases { get; set; }
        public System.DateTime otorgamiento { get; set; }
        public System.DateTime vencimiento { get; set; }
        public string observaciones { get; set; }
    
        public virtual categoria_licencia categoria_licencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infraccion> infraccions { get; set; }
        public virtual municipio municipio { get; set; }
        public virtual persona persona { get; set; }
    }
}
