//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseSiCoVe
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public persona()
        {
            this.cedulas = new HashSet<cedula>();
            this.licencias = new HashSet<licencia>();
            this.usuarios = new HashSet<usuario>();
            this.infraccions = new HashSet<infraccion>();
        }
    
        public int id { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public long dni { get; set; }
        public int sexo_id { get; set; }
        public int nacionalidad_id { get; set; }
        public int provincia_id { get; set; }
        public int localidad_id { get; set; }
        public string domicilio { get; set; }
        public Nullable<short> piso { get; set; }
        public string departamento { get; set; }
        public string nro_puerta { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string lugar_nacimiento { get; set; }
        public bool flag_conductor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cedula> cedulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<licencia> licencias { get; set; }
        public virtual localidad localidad { get; set; }
        public virtual nacionalidad nacionalidad { get; set; }
        public virtual provincia provincia { get; set; }
        public virtual sexo sexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario> usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infraccion> infraccions { get; set; }
    }
}
