//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseSiCoVe
{
    using System;
    using System.Collections.Generic;
    
    public partial class poliza
    {
        public int id { get; set; }
        public string nro_poliza { get; set; }
        public int aseguradora_id { get; set; }
        public int vehiculo_id { get; set; }
        public System.DateTime vigencia_desde { get; set; }
        public System.DateTime vigencia_hasta { get; set; }
    
        public virtual aseguradora aseguradora { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
