//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseSiCoVe
{
    using System;
    using System.Collections.Generic;
    
    public partial class poliza
    {
        public int id { get; set; }
        public string nro_poliza { get; set; }
        public int aseguradora_id { get; set; }
        public int vehiculo_id { get; set; }
        public Nullable<System.DateTime> vigencia_desde { get; set; }
        public Nullable<System.DateTime> vigencia_hasta { get; set; }
    
        public virtual aseguradora aseguradora { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
