//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseSiCoVe
{
    using System;
    using System.Collections.Generic;
    
    public partial class remolque
    {
        public int id { get; set; }
        public int personal_remolque_id { get; set; }
        public int playa_acarreo_id { get; set; }
        public Nullable<int> vehiculo_id { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string ubicacion { get; set; }
        public string detalle_infraccion { get; set; }
        public string dominio { get; set; }
        public int localidad_id { get; set; }
    
        public virtual localidad localidad { get; set; }
        public virtual personal_remolque personal_remolque { get; set; }
        public virtual playa_acarreo playa_acarreo { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
